apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    app: eureka
    tier: middleware
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 8761
  selector:
    app: eureka
    tier: middleware
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: middleware
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: eureka
    tier: middleware
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   app: guestbook
  #   tier: frontend
  template:
    metadata:
      labels:
        app: eureka
        tier: middleware
    spec:
      containers:
      - name: eureka-server
        image: springcloud/eureka
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: CONFIG_SERVER_URL
          value: http://config-server:8888
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        ports:
        - containerPort: 8761
      imagePullSecrets:
      - name: regcred
