apiVersion: v1
kind: Service
metadata:
  name: springboot-admin
  labels:
    app: springboot-admin
    tier: middleware
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 8080
  selector:
    app: springboot-admin
    tier: middleware
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: admin-middleware
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  #  labels:
  #  app: config
  #  tier: middleware
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   app: guestbook
  #   tier: frontend
  template:
    metadata:
      labels:
        app: springboot-admin
        tier: middleware
    spec:
      containers:
      - name: springboot-admin
        image: wvogt/spring-boot-admin       
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
